baseURL = "https://visiter-neuchatel.ch/"
languageCode = "fr"
title = "Visiter Neuch√¢tel"

disableKinds = ["taxonomy", "term", "robotsTXT", "RSS", "404"]

cleanDestinationDir = true

[minify]
minifyOutput = true